import { SiteConfig } from "@/types";

export const siteConfig: SiteConfig = {
  name: "ENOTRIUM",
  description: "A New Mesopotamia",
  nav: [
    { title: "Manifesto", href: "/manifesto" },
    { title: "Product", href: "#supply-chain" },
    { title: "Platform", href: "/" },
  ],
  hero: {
    title: "A New Mesopotamia",
    subtitle: "Autonomous Coordination for Critical Supply Chains",
  },
  manifesto: {
    date: "December 2025",
    title: "Manifesto",
    paragraphs: [
      "After the direct and indirect experience of the brokenness of our food supply, corporate overreach into agriculture, and the gradual downfall of rural America, it has become the responsibility of farmers and entrepreneurs to band together and form new systems of economic self-sovereignty which impel the Nation to its true destiny. To those who understand its importance, agriculture need not be explained, containing nothing less than America's left hand in national security and civil liberties on its right.",
      "The fate of America is the most interesting question in the world. What happens to our farmland, our food supply in the coming years will decide the fate of the nation.",
      "Farming as much as defense tech, energy, compute, and Industrial production shapes the economy and body politic. Agriculture is the intersection of all commerical production in any sound economy, it is the \"nursing mother of all sciences.\" At Enotrium we believe, our farmland was drained not by design, but as a strategy for uprooting America's economic freedom.",
      "Nearly 250 years after America's founding, it is often implied that modern Americans lack the will to rule themselves and direct the will of the nation to new heights. I reject this fatalism. I contest, like the Founders, for America to maintain its global standing we must adhere strictly to the creation of strong regional agricultural economies using all the cards we've been dealt. These cards include 900 million acres of arable farmland, the ease of direct communication, an immense capacity for building new technologies and regional transport between agricultural and industrial supply chains. Yet despite America's natural capacity of being the global agricultural powerhouse on the planet, yearly agricultural imports are approaching $300 billion, land is sold off to foreign investors, and farmers choose to grow nothing but corn and soy. Meanwhile Americans are battling chronic illness at rates never seen before. Foreign actors have inundated our supply chains with non-food ingredients, and unnamed chemicals are classified as proprietary and EPA approved. Chinese Agroterrorism has emerged with attacks on American farmland. Undisclosed suppliers deliver genetically modified pests and unnamed seeds around America, often laced with blight and toxic fungi. Well intending government agencies do not have the bandwidth to oversee global supply chains and prevent attacks, let alone verify quality and certify food grown abroad as organic.",
      "The Enotrium founders have taken it upon themselves to innovate on every level of commodity markets and deliver farmers and industrialists the technology necessary for rural America's restoration. In 2026, the globalist serfdom which has been imposed on us over the last half century will come to the beginning of its end. We declare here, the causes which have driven us to form The Enotrium Syndicate.",
      "The outdated nature of agricultural data management\nThe incompetence of federal and state departments in administering congressionally approved funding packages\nThe centralization and overt regulation on seed supplies and varieties\nA lack of investment in industrial commodity processing and decortication\nThe price control of commodity markets\nThe separation of equity markets and real markets\nThe non-insurability of any crop which may require less pesticides than GMO corn and GMO soy.\nIf we have misunderstood the nature of the problems in agriculture, farmers and industrialists will tell us. We heed their concerns as the direction for technological innovation. This is the only way we create the new economy for rural America. Any attempt of redress has gone ignored by investors, congress, and USDA. And from every form of agribusiness, farmers have faced nothing but schemes of profit and control.",
      "Because of this, we hold no false notions of technology and philanthropy. Farming is the most challenging business in the world, which is why less than 3 million Americans still choose to farm. Yet, the only path to preserving the liberty of the past is hard; the reindustrialization of America is industrial work. It is our happy fate to connect farmers to the technological innovations in autonomous processing, privacy preserving software, and encrypted data management.",
      "A strong agricultural economy is the foundation of America. This was implicit to the founders. Farmers and engineers, themselves, they understood without private property there is no freedom. Without regional commerce, there is no America, and without private channels for enterprise operations, ports and trade posts, there is no fair competition. Enotrium is the company which is giving rural America a chance to compete and to win. Silicon Valley is worth 5 trillion dollars. Tomorrow, now that certain innovations in processing have been made possible, rural America will be worth the same. The times have changed. When in the late twentieth century, our food supply was outsourced and small farms were drained, mega-corps told American farmers to compete, to compete with GMOs, to compete with commercial operations, to compete with slave wages in central America, to compete with rates well above operating margins, and to compete with regulations that enabled middle men wholesalers to upcharge.",
      "Today, the challenges faced in onshoring industrial applications of concrete, textiles, fiber, and energy is no different. We call upon every farmer in America to compete. 2025 is the year the incentives change. China is out of the U.S. grain market. And though this has costed the federal government tens of billions of dollars in soybean bailouts, China's withdrawal is a lit beacon signifying the end of a dying regime. For the first time in years, China hasn't purchased a single bushel of U.S. soy or corn. Certain analysts suggest this as a short-term retaliation; rather it is an early indicator of a shift in global agriculture and supply chains.",
      "This isn't simply about trade or tariffs — it's about what the future of agriculture will be, in the world and in America. The ripple effects extend well beyond the farm, reaching into the foundations of U.S. industrial production, where agricultural inputs, biotechnology, and data are connected, but most importantly industrial fiber and lignin. The U.S. agricultural sector isn't just facing a soybean arbitrage trade — it's entering a moment that will decide the fate of America. Enotrium and our generational partners have stewarded this destiny of America and are prepared for what is next.",
      "Thomas Jefferson knew \"Industrial Agriculture is of first necessity to the wealth and protection of the country.\"",
      "Yet among the most challenging operations which the new agrarian economy faces is coordination, commodity refinement and seed vetting. The answer is in the soil and seeds, not software alone, seeds which need tested and unrolled to every small farm.",
      "Today the US economy must return to its agrarian foundation: farming and manufacturing. Our national security depends on it. China's industrial fiber use in defense technology, construction markets and energy currently far exceeds the West's. Free trade absolutists and cost-cutting corporations have outsourced our food supplies to India, Brazil, Mexico and China, while giving our farming systems no investments or technological upgrades. This multi-decade long self-sabotage was not only at the expense of American farmers, but the health of every American. The solution in healing the soil resides here.",
      "The plan we have carried out, has yielded enough success to involve advancements in the supply chain. We consider our work at the heart of American industry and in the defense of the earth and the Nation. Even before innovations in autonomous processing, Ford asked,",
      "\"Why use up the forests, which were centuries in the making, and the mines which required ages to lay down, if we can get the equivalent of forest and mineral products in the annual growth of the kenaf fields?\n\n- Henry Ford, American Industrialist",
      "Multi-International Food conglomerates buy our land, pollute our soil, spray our crops with Chinese chemicals as they call Americans fat and sick. Modern America has given corporations the right to privacy and freedom, before her citizens. The only solution is rebellion; Enotrium exists to give farmers and industrialists weapons grade software and end-to-end control of their operations. Furthermore, transparency of our supplies, including non-food ingredients and contaminants are a right to health and a safeguard to US supply chains. The age of the grain oligopolies will end because they have failed to connect agriculture to the most important American industries: AI, defense, construction and robotics. For the first time in decades, we have the perfect shot to reset America's industrial base and onshore critical farming operations under American companies. The alternatives we know all too well. This corporate extraction of our land will end.",
      "\"Indeed we ought firmly to believe, what is an undoubted truth, confirmed by the unhappy experience of many states heretofore free, that unless the most watchful attention be exerted, a new servitude may be slipped upon us, under the sanction of usual and respectable terms.\n\nThus the Cæsars ruined the Roman liberty, under the titles of tribunicial and dictatorial authorities — -old and venerable dignities, known in the most flourishing times of freedom.\"\n\n-Letters from a Pennsylvania Farmer, John Dickinson",
      "Clean and regional food supplies, all American grown are no longer to be thought of as a luxury, but a basic foundation to national security and individual liberty. Farming is the foundation of every industry which will secure critical inputs, protect innovation, and sustain competitiveness in the next generation of world economy. American farmland will no longer be disconnected from the most important industries in the world, farmers are the first step in a supply chain critical to the economic success of the nation.",
      "Recently, the HLB \"citrus greening\" bacteria destroyed most of the Florida orange industry. The US cannot remain dependent on foreign supply chains, seed suppliers and mono-cropping industrialists who have not defended American farmers in the past and do not have the foresight to do so in the future.",
      "American farmers are one season away from an act of agro-terrorism bacteria outbreak wiping out a crop cycle. Moreover, ag-tech and biotech companies are marketing proprietary synthetic fertilizer alternatives as the future of nitrogen and fungicide treatments. Farmers do not trust lab trials, and should have the technological framework to run their own open-source field trials.",
      "At a time, like all times, when rural America is attacked and ignored by lawmakers, banks and technology investors, Enotrium is defending farmers, an early and imperfect attempt it may be, to end the extractive serfdom of the original American industry, make amends for the past and give farmers total control over American supply chains. Everyone in agriculture understood, the challenge for an industrial fiber based economy was processing. Today, Enotrium has overcome that challenge.",
      "Enotrium Founder & CEO, Aiden Young",
    ],
  },
  supplyChain: {
    label: "INFRASTRUCTURE",
    title: ["Industrial", "Supply Chain", "Mastery"],
    description:
      "Orchestrating the backbone of American industry. From raw materials to finished goods, our platform enables seamless coordination across the entire supply chain ecosystem.",
    commodities: ["AGRICULTURE", "MANUFACTURING", "DEFENSE", "CONSTRUCTION",],
    stats: [
      { label: "Industries", value: "4", sub: "Sectors" },
      { label: "Partners", value: "34", sub: "Networks" },
      { label: "Coverage", value: "30", sub: "States" },
    ],
  },
  contact: {
    ctaHref: "https://calendly.com/enotrium/demo",
  },
};
