import type { Metadata } from "next";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Terms of Use",
};

export default function TermsOfUsePage() {
  return (
    <div className="bg-black text-white min-h-screen font-[family-name:var(--font-inter)]">
      <Navbar />

      <main className="pt-32 pb-24 px-6 lg:px-16 max-w-[900px] mx-auto">
        <p className="text-[10px] font-semibold tracking-[0.25em] uppercase text-neutral-500 mb-8">
          Terms of Use
        </p>

        <h1 className="text-3xl sm:text-4xl font-bold mb-4">
          Terms and Conditions
        </h1>
        <p className="text-xs text-neutral-500 mb-12">
          Last updated: February 25, 2026
        </p>

        <div className="space-y-10 text-xs leading-relaxed text-neutral-300">
          <section>
            <p className="mb-4">
              Please read these Terms and Conditions carefully before using our Service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-4">Interpretation and Definitions</h2>
            
            <h3 className="text-sm font-bold text-white mb-2">Interpretation</h3>
            <p className="mb-4">
              Words with capitalized initial letters have meanings defined under the following conditions. These definitions apply whether the terms appear in singular or plural.
            </p>

            <h3 className="text-sm font-bold text-white mb-2">Definitions</h3>
            <p className="mb-2">For the purposes of these Terms and Conditions:</p>
            <ul className="space-y-2 ml-4 list-disc marker:text-neutral-500">
              <li><strong className="text-white">Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party.</li>
              <li><strong className="text-white">Country</strong> refers to: United States</li>
              <li><strong className="text-white">Company</strong> refers to Enotrium</li>
              <li><strong className="text-white">Device</strong> means any device that can access the Service</li>
              <li><strong className="text-white">Feedback</strong> means feedback, innovations, or suggestions</li>
              <li><strong className="text-white">Service</strong> refers to the Website and any associated software, APIs, models, or systems</li>
              <li><strong className="text-white">AI Systems</strong> means machine learning models, pipelines, inference systems, datasets, or related infrastructure provided by the Company</li>
              <li><strong className="text-white">Data</strong> means any information, datasets, inputs, or outputs processed through the Service</li>
              <li><strong className="text-white">Terms</strong> means this agreement</li>
              <li><strong className="text-white">Website</strong> refers to https://www.enotrium.org</li>
              <li><strong className="text-white">You</strong> means the user or entity using the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-4">Acknowledgment</h2>
            <ul className="space-y-2 ml-4 list-disc marker:text-neutral-500">
              <li>By accessing or using the Service, You agree to be bound by these Terms.</li>
              <li>You must be at least 18 years old to use the Service.</li>
              <li>Your use is also conditioned on acceptance of our Privacy Policy.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-4">Intellectual Property</h2>
            <p className="mb-2">
              All content, software, AI Systems, models, datasets, and infrastructure are the exclusive property of the Company.
            </p>
            <p className="mb-2">This includes:</p>
            <ul className="space-y-1 ml-4 list-disc marker:text-neutral-500">
              <li>Model architectures</li>
              <li>Training pipelines</li>
              <li>Hyperspectral and sensing datasets</li>
              <li>Outputs generated by proprietary systems</li>
            </ul>
            <p className="mt-4">
              These are protected under copyright, trade secret, and other applicable laws.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-4">AI Systems and Data Usage</h2>
            
            <h3 className="text-sm font-bold text-white mb-2">Permitted Use</h3>
            <p className="mb-4">
              You are granted a limited, non-exclusive, non-transferable license to use the Service for lawful purposes.
            </p>

            <h3 className="text-sm font-bold text-white mb-2">Restrictions</h3>
            <p className="mb-2">You agree NOT to:</p>
            <ul className="space-y-1 ml-4 list-disc marker:text-neutral-500">
              <li>Reverse engineer, decompile, or extract models or weights</li>
              <li>Attempt to recreate or replicate the Service or AI Systems</li>
              <li>Use outputs to train competing models</li>
              <li>Perform model extraction, inference attacks, or dataset reconstruction</li>
              <li>Scrape, harvest, or systematically collect data from the Service</li>
              <li>Use the Service for surveillance, weapons development, or unlawful activity</li>
            </ul>

            <h3 className="text-sm font-bold text-white mb-2 mt-4">Model Output and Responsibility</h3>
            <p className="mb-2">Outputs generated by the Service:</p>
            <ul className="space-y-1 ml-4 list-disc marker:text-neutral-500">
              <li>May be probabilistic and not guaranteed accurate</li>
              <li>Do not constitute professional, scientific, or operational advice</li>
              <li>Are used at Your own risk</li>
            </ul>
            <p className="mt-2">
              The Company is not liable for decisions made based on outputs.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-4">Data Rights and Usage</h2>
            <p className="mb-2">
              By using the Service, You grant the Company a license to:
            </p>
            <ul className="space-y-1 ml-4 list-disc marker:text-neutral-500">
              <li>Process, analyze, and store input Data</li>
              <li>Improve models and systems</li>
              <li>Generate aggregated or anonymized insights</li>
            </ul>
            <p className="mt-4">
              We will not sell personally identifiable data without consent.
            </p>

            <h3 className="text-sm font-bold text-white mb-2 mt-4">Sensitive and Restricted Data</h3>
            <p className="mb-2">You agree NOT to submit:</p>
            <ul className="space-y-1 ml-4 list-disc marker:text-neutral-500">
              <li>Classified or export-controlled data</li>
              <li>Personal health or biometric data without authorization</li>
              <li>Data subject to regulatory protection (unless compliant)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-4">Export Controls and Compliance</h2>
            <p className="mb-4">
              You agree to comply with all applicable export control laws, including those of the United States.
            </p>
            <p className="mb-2">You may not use or access the Service if You are:</p>
            <ul className="space-y-1 ml-4 list-disc marker:text-neutral-500">
              <li>Located in a sanctioned jurisdiction</li>
              <li>Listed on restricted or denied parties lists</li>
            </ul>
            <p className="mt-4">The Service may not be used for:</p>
            <ul className="space-y-1 ml-4 list-disc marker:text-neutral-500">
              <li>Military targeting systems</li>
              <li>Autonomous weapons</li>
              <li>Prohibited surveillance applications</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-4">Commercial Use and API Access</h2>
            <p className="mb-4">
              Use of the Service for commercial purposes may require a separate agreement.
            </p>
            <p className="mb-2">You may NOT:</p>
            <ul className="space-y-1 ml-4 list-disc marker:text-neutral-500">
              <li>Resell or sublicense access</li>
              <li>Embed the Service into a commercial product without permission</li>
              <li>Use the Service as backend infrastructure for another platform</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-4">Feedback</h2>
            <p>
              You assign all rights in Feedback to the Company, or grant a perpetual, royalty-free license.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-4">Third-Party Links</h2>
            <p>
              We are not responsible for third-party services linked through the Service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-4">Termination</h2>
            <p className="mb-2">We may suspend or terminate access at any time, including for:</p>
            <ul className="space-y-1 ml-4 list-disc marker:text-neutral-500">
              <li>Violations of these Terms</li>
              <li>Suspected misuse of AI Systems</li>
              <li>Security risks</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-4">Limitation of Liability</h2>
            <p className="mb-2">Liability is limited to:</p>
            <ul className="space-y-1 ml-4 list-disc marker:text-neutral-500">
              <li>Amount paid by You, or</li>
              <li>$100 USD</li>
            </ul>
            <p className="mt-4">
              We are not liable for indirect, incidental, or consequential damages.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-4">AS IS Disclaimer</h2>
            <p className="mb-4">
              The Service is provided without warranties of any kind.
            </p>
            <p className="mb-2">We do not guarantee:</p>
            <ul className="space-y-1 ml-4 list-disc marker:text-neutral-500">
              <li>Accuracy</li>
              <li>Reliability</li>
              <li>Security</li>
              <li>Fitness for purpose</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-4">Governing Law</h2>
            <p>
              These Terms are governed by the laws of the United States.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-4">Dispute Resolution</h2>
            <p>
              You agree to first attempt informal resolution by contacting: <a href="mailto:contact@enotrium.org" target="_self" className="text-white hover:text-neutral-400 transition-colors">contact@enotrium.org</a>
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-4">United States Legal Compliance</h2>
            <p className="mb-2">You certify that You are not:</p>
            <ul className="space-y-1 ml-4 list-disc marker:text-neutral-500">
              <li>In a sanctioned country</li>
              <li>On a restricted parties list</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-4">Severability and Waiver</h2>
            <ul className="space-y-2 ml-4 list-disc marker:text-neutral-500">
              <li>Invalid provisions will be modified to remain enforceable.</li>
              <li>Failure to enforce a provision does not waive rights.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-4">Changes to Terms</h2>
            <ul className="space-y-2 ml-4 list-disc marker:text-neutral-500">
              <li>We may update these Terms at any time.</li>
              <li>Material changes will be communicated with reasonable notice.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-4">Contact</h2>
            <p>
              <a href="mailto:contact@enotrium.org" target="_self" className="text-white hover:text-neutral-400 transition-colors">contact@enotrium.org</a>
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
